from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from zipfile import ZipFile

from docx import Document


ROOT = Path(__file__).resolve().parents[1]
APP_DIR = ROOT / "app"
OUT_DIR = ROOT / "outputs"
GENERATED_DIR = APP_DIR / "generated"

sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(APP_DIR))

from build_maintenance_quick_template_v5 import build_workbook  # noqa: E402
from doc_generator import generate_p2_m01_pdf_package  # noqa: E402
from excel_parser import parse_excel  # noqa: E402
from rules import suggest_maintenance  # noqa: E402


JOB_CODE = "M01-FULL-STRESS"
WORKBOOK_PATH = OUT_DIR / "M01_full_stress_input.xlsx"
AUDIT_PATH = OUT_DIR / "M01_full_stress_audit_report.json"


def clean(value):
    return "" if value is None else str(value).strip()


def field_key_from_header(value) -> str:
    raw = clean(value)
    if not raw:
        return ""
    for part in reversed(re.split(r"[\r\n]+", raw)):
        part = part.strip().strip("()[] ")
        if re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", part):
            return part
    compact = re.sub(r"[^A-Za-z0-9_]", "", raw)
    return compact if re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", compact) else raw


def sheet_by_index(wb, index: int):
    return wb.worksheets[index]


def set_vertical(ws, values: dict[str, object]) -> None:
    for row in range(1, ws.max_row + 1):
        key = clean(ws.cell(row, 3).value)
        if key in values:
            ws.cell(row, 4).value = values[key]


def set_transposed(ws, records: list[dict[str, object]], start_col: int = 5) -> None:
    key_to_row: dict[str, int] = {}
    for row in range(1, ws.max_row + 1):
        key = clean(ws.cell(row, 3).value)
        if key:
            key_to_row[key] = row
    for idx, record in enumerate(records):
        col = start_col + idx
        ws.cell(3, col).value = f"Test {idx + 1}"
        for key, value in record.items():
            row = key_to_row.get(key)
            if row:
                ws.cell(row, col).value = value


def set_table(ws, records: list[dict[str, object]], start_row: int = 2) -> None:
    keys = [field_key_from_header(ws.cell(1, col).value) for col in range(1, ws.max_column + 1)]
    for row in range(start_row, max(ws.max_row, start_row + len(records) + 5) + 1):
        for col in range(1, ws.max_column + 1):
            ws.cell(row, col).value = None
    for idx, record in enumerate(records):
        row = start_row + idx
        for col, key in enumerate(keys, start=1):
            if key in record:
                ws.cell(row, col).value = record[key]


def build_stress_workbook() -> Path:
    wb = build_workbook(False)

    company_ws = sheet_by_index(wb, 1)
    people_ws = sheet_by_index(wb, 2)
    company_change_ws = sheet_by_index(wb, 3)
    person_action_ws = sheet_by_index(wb, 4)
    personal_particular_ws = sheet_by_index(wb, 5)
    transfer_in_ws = sheet_by_index(wb, 6)
    share_transfer_ws = sheet_by_index(wb, 7)
    allotment_ws = sheet_by_index(wb, 8)
    annual_ws = sheet_by_index(wb, 9)
    shareholder_ws = sheet_by_index(wb, 10)
    output_ws = sheet_by_index(wb, 12)

    long_old_address = (
        "8 TEMASEK BOULEVARD, #35-01 SUNTEC TOWER THREE, "
        "SINGAPORE 038988"
    )
    long_new_address = (
        "71 ROBINSON ROAD, #14-01, SINGAPORE 068895, "
        "CARE OF RSIN GROUP CORPORATE SECRETARY DEPARTMENT, "
        "ATTENTION: STATUTORY RECORDS TEAM"
    )

    set_vertical(
        company_ws,
        {
            "business_order_id": JOB_CODE,
            "source_type": "Manual stress test",
            "source_file_id": "Generated by Codex regression script",
            "company_name": "M01 FULL STRESS TEST PTE. LTD.",
            "uen": "202699999Z",
            "registered_office_address": long_old_address,
            "default_document_date": "03/06/2026",
            "current_secretary_company": "OLD SECRETARY SERVICES PTE. LTD.",
            "new_secretary_company": "RSIN GROUP PTE. LTD.",
            "contact_person_id": "P001",
            "client_signatory_person_id": "P001",
            "director_signer_person_id": "",
            "prepared_by": "Codex M01 stress test",
            "notes": "Stress test covering all currently supported M01 ordinary DR sections.",
        },
    )

    set_transposed(
        people_ws,
        [
            {
                "person_id": "P001",
                "source": "new",
                "full_name": "TAN CURRENT DIRECTOR",
                "id_type": "NRIC",
                "id_number": "S1111111A",
                "nationality": "Singaporean",
                "residential_address": (
                    "1 RAFFLES PLACE, #20-61 ONE RAFFLES PLACE, "
                    "SINGAPORE 048616"
                ),
                "email": "tan.current@example.com",
                "phone": "+65 9000 0001",
                "current_roles": "Director / Shareholder / Client signatory",
                "is_director": "Yes",
                "is_secretary": "No",
                "is_shareholder": "Yes",
                "is_client_signatory": "Yes",
                "remarks": "Main client-side director signer for M01.",
            },
            {
                "person_id": "P002",
                "source": "new",
                "full_name": "LEE RESIGNING DIRECTOR",
                "id_type": "Passport",
                "id_number": "P98765432",
                "nationality": "Malaysian",
                "residential_address": (
                    "UNIT 25-08, VERY LONG INTERNATIONAL BUSINESS RESIDENCE, "
                    "88 JALAN SULTAN ISMAIL, KUALA LUMPUR 50250, MALAYSIA"
                ),
                "email": "lee.old@example.com",
                "phone": "+60 12 345 6789",
                "current_roles": "Director",
                "is_director": "Yes",
                "is_secretary": "No",
                "is_shareholder": "No",
                "is_client_signatory": "No",
                "remarks": "Resignation test with long foreign address.",
            },
            {
                "person_id": "P003",
                "source": "new",
                "full_name": "WONG NEW DIRECTOR",
                "id_type": "FIN",
                "id_number": "G1234567B",
                "nationality": "Chinese",
                "residential_address": (
                    "23 MARINA WAY, #45-12 MARINA ONE RESIDENCES, "
                    "SINGAPORE 018979"
                ),
                "email": "wong.new@example.com",
                "phone": "+65 9000 0003",
                "current_roles": "Proposed Director",
                "is_director": "No",
                "is_secretary": "No",
                "is_shareholder": "No",
                "is_client_signatory": "No",
                "remarks": "Appointment test person.",
            },
            {
                "person_id": "P004",
                "source": "new",
                "full_name": "OLD SECRETARY LIM",
                "id_type": "NRIC",
                "id_number": "S2222222B",
                "nationality": "Singaporean",
                "residential_address": (
                    "10 ANSON ROAD, #18-08 INTERNATIONAL PLAZA, "
                    "SINGAPORE 079903"
                ),
                "email": "old.secretary@example.com",
                "phone": "+65 9000 0004",
                "current_roles": "Company Secretary",
                "is_director": "No",
                "is_secretary": "Yes",
                "is_shareholder": "No",
                "is_client_signatory": "No",
                "remarks": "Secretary resignation test.",
            },
            {
                "person_id": "P005",
                "source": "new",
                "full_name": "NEW SECRETARY CHEN",
                "id_type": "NRIC",
                "id_number": "S3333333C",
                "nationality": "Singaporean",
                "residential_address": (
                    "6 BATTERY ROAD, #30-01, SINGAPORE 049909"
                ),
                "email": "new.secretary@example.com",
                "phone": "+65 9000 0005",
                "current_roles": "Proposed Company Secretary",
                "is_director": "No",
                "is_secretary": "No",
                "is_shareholder": "No",
                "is_client_signatory": "No",
                "remarks": "Secretary appointment test.",
            },
            {
                "person_id": "P006",
                "source": "new",
                "full_name": "LIM TRANSFEREE SHAREHOLDER",
                "id_type": "Passport",
                "id_number": "E76543210",
                "nationality": "Indonesian",
                "residential_address": (
                    "99 ORCHARD ROAD, #08-88, SINGAPORE 238888"
                ),
                "email": "lim.transferee@example.com",
                "phone": "+65 9000 0006",
                "current_roles": "Incoming Shareholder",
                "is_director": "No",
                "is_secretary": "No",
                "is_shareholder": "No",
                "is_client_signatory": "No",
                "remarks": "Share transfer transferee.",
            },
            {
                "person_id": "P007",
                "source": "new",
                "full_name": "ONG ALLOTTEE INVESTOR",
                "id_type": "Passport",
                "id_number": "K11223344",
                "nationality": "Australian",
                "residential_address": (
                    "12 CECIL STREET, #18-08, SINGAPORE 049705"
                ),
                "email": "ong.allottee@example.com",
                "phone": "+65 9000 0007",
                "current_roles": "New Allottee",
                "is_director": "No",
                "is_secretary": "No",
                "is_shareholder": "No",
                "is_client_signatory": "No",
                "remarks": "Allotment test person.",
            },
        ],
    )

    set_vertical(
        company_change_ws,
        {
            "change_registered_office_required": "Yes",
            "old_registered_office_address": long_old_address,
            "new_registered_office_address": long_new_address,
            "change_business_activity_required": "Yes",
            "old_primary_ssic": "70201",
            "old_primary_activity": "MANAGEMENT CONSULTANCY SERVICES",
            "new_primary_ssic": "62011",
            "new_primary_activity": (
                "DEVELOPMENT OF SOFTWARE AND APPLICATIONS "
                "EXCEPT GAMES AND CYBERSECURITY"
            ),
            "old_secondary_ssic": "62019",
            "old_secondary_activity": (
                "OTHER INFORMATION TECHNOLOGY AND COMPUTER SERVICE ACTIVITIES"
            ),
            "new_secondary_ssic": "63119",
            "new_secondary_activity": (
                "DATA PROCESSING, HOSTING AND RELATED ACTIVITIES "
                "INCLUDING CLOUD-BASED BUSINESS AUTOMATION"
            ),
            "change_fye_required": "Yes",
            "old_fye": "31/12/2025",
            "new_fye": "30/06/2026",
            "next_accounts_period_start": "01/01/2026",
            "next_accounts_period_end": "30/06/2026",
            "change_office_hours_required": "Yes",
            "new_office_hours": (
                "Monday to Friday, 10.00 a.m. to 4.00 p.m., "
                "excluding Singapore public holidays"
            ),
        },
    )

    set_table(
        person_action_ws,
        [
            {
                "generate": "Yes",
                "action_type": "resign_director",
                "target_person_id": "P002",
                "target_name": "LEE RESIGNING DIRECTOR",
                "effective_date": "03/06/2026",
                "resignation_letter": "Yes",
                "remarks": "Director resignation with optional resignation letter.",
            },
            {
                "generate": "Yes",
                "action_type": "appoint_director",
                "target_person_id": "P003",
                "target_name": "WONG NEW DIRECTOR",
                "effective_date": "03/06/2026",
                "resignation_letter": "No",
                "remarks": "Appointment of new director.",
            },
            {
                "generate": "Yes",
                "action_type": "resign_secretary",
                "target_person_id": "P004",
                "target_name": "OLD SECRETARY LIM",
                "effective_date": "03/06/2026",
                "resignation_letter": "Yes",
                "remarks": "Secretary resignation.",
            },
            {
                "generate": "Yes",
                "action_type": "appoint_secretary",
                "target_person_id": "P005",
                "target_name": "NEW SECRETARY CHEN",
                "effective_date": "03/06/2026",
                "resignation_letter": "No",
                "remarks": "Appointment of new secretary.",
            },
        ],
    )

    set_table(
        personal_particular_ws,
        [
            {
                "generate": "Yes",
                "target_person_id": "P001",
                "target_name": "TAN CURRENT DIRECTOR",
                "field_label": "ID number",
                "old_value": "S1111111A",
                "new_value": "S1111111B",
                "effective_date": "03/06/2026",
                "remarks": "NRIC number update test.",
            },
            {
                "generate": "Yes",
                "target_person_id": "P001",
                "target_name": "TAN CURRENT DIRECTOR",
                "field_label": "Residential address",
                "old_value": (
                    "1 RAFFLES PLACE, #20-61 ONE RAFFLES PLACE, "
                    "SINGAPORE 048616"
                ),
                "new_value": (
                    "9 STRAITS VIEW, #12-07 MARINA ONE WEST TOWER, "
                    "SINGAPORE 018937"
                ),
                "effective_date": "03/06/2026",
                "remarks": "Long local address update test.",
            },
            {
                "generate": "Yes",
                "target_person_id": "P002",
                "target_name": "LEE RESIGNING DIRECTOR",
                "field_label": "Email",
                "old_value": "lee.old@example.com",
                "new_value": "lee.updated@example.com",
                "effective_date": "03/06/2026",
                "remarks": "Multiple officer particular update test.",
            },
        ],
    )

    set_vertical(
        transfer_in_ws,
        {
            "transfer_in_required": "No",
            "transfer_in_mode": "cooperative",
            "generate_handover_letter": "No",
            "generate_resignation_letter": "No",
            "remarks": "Not part of M01 stress test; reserved for M02.",
        },
    )

    set_table(
        share_transfer_ws,
        [
            {
                "generate": "Yes",
                "transferor_name": "TAN CURRENT DIRECTOR",
                "transferee_name": "LIM TRANSFEREE SHAREHOLDER",
                "share_class": "Ordinary",
                "shares_transferred": 250,
                "transfer_date": "03/06/2026",
                "consideration_basis": "acra_paid_value",
                "cash_consideration": "0",
                "old_certificate_no": "001",
                "new_certificate_no": "002",
                "stamp_duty_review": "No",
                "remarks": "Internal transfer; M01 only approves transfer.",
            }
        ],
    )

    set_table(
        allotment_ws,
        [
            {
                "generate": "Yes",
                "allottee_person_id": "P007",
                "allottee_name": "ONG ALLOTTEE INVESTOR",
                "share_class": "Ordinary",
                "shares_allotted": 500,
                "amount_paid_per_share": 1,
                "total_paid": 500,
                "currency": "SGD",
                "allotment_date": "03/06/2026",
                "authority_date": "03/06/2026",
                "form24_required": "Yes",
                "certificate_no": "003",
                "remarks": "Allotment approval only; Form 24 handled by later package.",
            }
        ],
    )

    set_vertical(
        annual_ws,
        {
            "annual_review_required": "No",
            "remarks": "Annual review intentionally disabled for pure M01 stress test.",
        },
    )

    set_transposed(
        shareholder_ws,
        [
            {
                "shareholder_id": "SH001",
                "shareholder_type": "person",
                "person_id": "P001",
                "shareholder_name": "TAN CURRENT DIRECTOR",
                "id_or_reg_no": "S1111111A",
                "share_class": "Ordinary",
                "shares": 1000,
                "paid_amount": 1000,
                "currency": "SGD",
                "certificate_no": "001",
                "is_current": "Yes",
                "remarks": "Existing shareholder before transfer.",
            },
            {
                "shareholder_id": "SH002",
                "shareholder_type": "person",
                "person_id": "P006",
                "shareholder_name": "LIM TRANSFEREE SHAREHOLDER",
                "id_or_reg_no": "E76543210",
                "share_class": "Ordinary",
                "shares": 0,
                "paid_amount": 0,
                "currency": "SGD",
                "certificate_no": "",
                "is_current": "No",
                "remarks": "Incoming transferee.",
            },
            {
                "shareholder_id": "SH003",
                "shareholder_type": "person",
                "person_id": "P007",
                "shareholder_name": "ONG ALLOTTEE INVESTOR",
                "id_or_reg_no": "K11223344",
                "share_class": "Ordinary",
                "shares": 0,
                "paid_amount": 0,
                "currency": "SGD",
                "certificate_no": "",
                "is_current": "No",
                "remarks": "Incoming allottee.",
            },
        ],
    )

    set_vertical(
        output_ws,
        {
            "package": "AUTO_MAINTENANCE_V5",
            "output_format": "pdf_zip",
            "generate_internal_checklist": "Yes",
            "notes": "Full M01 stress package.",
        },
    )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    wb.save(WORKBOOK_PATH)
    return WORKBOOK_PATH


def extract_docx_text(docx_path: Path) -> str:
    doc = Document(docx_path)
    chunks: list[str] = []
    for paragraph in doc.paragraphs:
        chunks.append(paragraph.text)
    for table in doc.tables:
        for row in table.rows:
            chunks.append(" | ".join(cell.text for cell in row.cells))
    return "\n".join(chunks)


def audit_outputs(parsed: dict, zip_path: Path) -> dict:
    code = JOB_CODE
    docx_dir = GENERATED_DIR / f"{code}_P2_M01_docs"
    pdf_dir = GENERATED_DIR / f"{code}_P2_M01_pdf"
    docx_files = sorted(docx_dir.glob("*.docx"))
    pdf_files = sorted(pdf_dir.glob("*.pdf"))
    docx_text = extract_docx_text(docx_files[0]) if docx_files else ""

    required_needles = {
        "company_name": "M01 FULL STRESS TEST PTE. LTD.",
        "uen": "202699999Z",
        "registered_office_new": "71 ROBINSON ROAD",
        "office_hours": "10.00 a.m. to 4.00 p.m.",
        "primary_ssic_new": "62011",
        "secondary_ssic_new": "63119",
        "new_fye": "30/06/2026",
        "officer_particulars_heading": "the following officer(s)",
        "id_number_update": "S1111111B",
        "new_director": "WONG NEW DIRECTOR",
        "resigning_director": "LEE RESIGNING DIRECTOR",
        "new_secretary": "NEW SECRETARY CHEN",
        "resigning_secretary": "OLD SECRETARY LIM",
        "share_transfer": "250",
        "transferee": "LIM TRANSFEREE SHAREHOLDER",
        "allottee": "ONG ALLOTTEE INVESTOR",
        "share_allotment": "500",
        "signer": "TAN CURRENT DIRECTOR",
        "bizfile": "BizFile",
    }
    docx_text_lower = docx_text.lower()
    needle_results = {key: value.lower() in docx_text_lower for key, value in required_needles.items()}

    unresolved_patterns = [r"\{\{", r"\}\}", r"\[\[", r"\]\]", r"\bNone\b", r"\bnull\b"]
    unresolved_hits = {
        pattern: re.findall(pattern, docx_text, flags=re.IGNORECASE)
        for pattern in unresolved_patterns
    }
    unresolved_hits = {key: value for key, value in unresolved_hits.items() if value}

    preview = suggest_maintenance(parsed)
    summary_path = docx_dir / "generation_summary.json"
    generation_summary = json.loads(summary_path.read_text(encoding="utf-8")) if summary_path.exists() else {}
    director_signers = generation_summary.get("director_signers", [])
    package_names: list[str] = []
    if zip_path.exists():
        with ZipFile(zip_path, "r") as zf:
            package_names = zf.namelist()

    return {
        "input_workbook": str(WORKBOOK_PATH),
        "job_code": JOB_CODE,
        "docx_files": [str(path) for path in docx_files],
        "pdf_files": [str(path) for path in pdf_files],
        "pdf_zip": str(zip_path),
        "pdf_zip_entries": package_names,
        "detected_changes": preview.get("detected_changes", []),
        "preview_summary": preview.get("summary", {}),
        "director_signers": director_signers,
        "director_signer_check": {
            "expected": ["TAN CURRENT DIRECTOR", "LEE RESIGNING DIRECTOR"],
            "unexpected": [],
            "passed": director_signers == ["TAN CURRENT DIRECTOR", "LEE RESIGNING DIRECTOR"],
        },
        "expected_text_checks": needle_results,
        "missing_expected_text": [
            key for key, ok in needle_results.items() if not ok
        ],
        "unresolved_placeholder_hits": unresolved_hits,
        "docx_character_count": len(docx_text),
        "audit_notes": [
            "M01 covers ordinary directors' resolution approval only.",
            "resignation_letter=Yes is an instruction for a separate resignation letter package; it is not included in the M01 PDF.",
            "Share transfer instruments, Form 24, share certificates and transfer-in EGM documents are separate packages.",
            "This stress test intentionally combines many matters into one DR to expose field and layout issues.",
        ],
    }


def main() -> None:
    workbook_path = build_stress_workbook()
    parsed = parse_excel(workbook_path, {})
    zip_path = generate_p2_m01_pdf_package(parsed, JOB_CODE)
    audit = audit_outputs(parsed, zip_path)
    AUDIT_PATH.write_text(json.dumps(audit, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(audit, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
